### ISSUE TITLE
Redesign feedback response

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-frontend#1014]
Round of updates as response to compiled user feedback

- [ ] ~~Fix chart overflow~~
- [x] Reduce text and padding, desktop and mobile in [pool details page](https://www.figma.com/file/7iWExDLY1u7kClXZwS3OZI/Pool-Details-%26-Modals?node-id=1%3A4&t=UJGI3mCZcAQQ8hHD-1), [assets page](https://www.figma.com/file/TbhltqFzPjWgIdxdcQ23dj/Assets?node-id=46%3A811&t=qk9d12GtN8jGSl8t-0#316619125), and [pools page](https://www.figma.com/file/ddlsIdRm0p30bFC5Lyt5OA/Pools?node-id=1%3A3&t=HbINXzyCfEpDqwdB-0) (#1081)
- [x] Show [user pool asset composition](https://www.figma.com/file/7iWExDLY1u7kClXZwS3OZI/Pool-Details-%26-Modals?node-id=922%3A28838&t=UJGI3mCZcAQQ8hHD-1) (#1070)
- [x] Include staked assets in total assets amount (#1088)
- [x] OSMO price and buy button in sidebar (#1083)
- [x] New token select in swap widget (#1042)
- [x] Scollbars on windows (#1058)
- [x] Dropshadow to separate elements; settings panel, slippage settings dropdown (#1063)
- [ ] ~~Issue #1029~~
- [x] Issue #1031 (#1061)
- [x] Only filter pools (not assets) $<.01 in user settings, update copy

[Buy OSMO design](https://www.figma.com/file/a1FycJWJ7VARpWMfzoCQF1/UI-Refresh-Aug-2022?node-id=446%3A4638&t=b7nO39wrdkviLozw-4)
[Pool detail page design](https://www.figma.com/file/7iWExDLY1u7kClXZwS3OZI/Pool-Details-%26-Modals?node-id=1%3A4&t=vCv8lGGXSvcJdNXi-1)
[Core components (drop shadows)](https://www.figma.com/file/kYSFzlWoiMFrqkF46dtZQV/Osmosis-Design-Guidelines-2022?node-id=307%3A3795&t=glYfKmBbseUawn45-1)
[Trade UI new token select](https://www.figma.com/file/om93lu8iXOhxwGHSUpAXEP/Trade-UI?node-id=896%3A8188&t=Y83ZuwqoelpGzMmI-4)

**Comment by jonator** [comment]
Current WIP on branch `jonator/redesign-response`
