### ISSUE TITLE
Osmosis App Documentation

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis-frontend#109]
## Challenge
The documentation for the frontend is work in progress and needs work and step by step guides. 

## Solution
Create the following guides in order for users to fully understand the process from beginning to end. 

## Docs pPreview
https://osmosis-labs.github.io/osmosis/overview/

## TODO/Goals
- [x] Update Structure to match the one below [Commit](https://github.com/osmosis-labs/osmosis/commit/b568534baf8b7cdbbbbba676b2ab531a8128124c)
- [x] Finish up all docs for each section 
- [ ] Add  video tutorials to display on the getting started page.

## OSMOSIS  APP Documentation Structure
- [x] Getting Started
    - [x] Open the App
    - [x] Connect Wallet
    - [x] Deposit Funds
    - [x] Swapping Tokens
    - [x] Create a New Pool
- [x] Adding Liquidity to a Pool
    - [x] Bonding LP Tokens 
- [x] Learn More
    - [x] Bonded Liquidity Gauges
    - [x] Allocation Points
    - [x] External Incentives
    - [x] Fees
- [ ] Wallet
    - [x] Create Keplr Wallet
    - [x] Import a Keplr account
    - [x] Import a Ledger account

**Comment by daniel-farina** [comment]
A lot of the docs from this guide were originally hosted https://osmosis.gitbook.io/o/ and were created by John Patten.  I would like to create a credits section on the documentation to make sure we give credits to all contributors.

**Comment by daniel-farina** [comment]
I did a major cleanup of the ticket to focus only on the app's doc from a user perspective. There will be another ticket for documentation from a dev's point of view. 

This is what it looks like so far, still a lot of work to do:
![image](https://user-images.githubusercontent.com/13665117/144341037-833e29e5-dedf-4729-bf1b-563c68cd4930.png)

**Comment by dogemos** [comment]
closing this as it seems all the sections are complete. thank you so much @daniel-farina!
