### ISSUE TITLE
[EPIC] frontier.osmosis.zone checklist

### ISSUE THREAD

**Issue by dogemos** [osmosis-labs/osmosis-frontend#337]
- [x] Color scheme modification (@victortokaito)
- [ ] Trade page image replacement 
- [ ] Remove non-incentivized assets from app.osmosis.zone (cc @JeremyParish69)
- [ ] Remove non-incentivized assets from trade router (cc @JeremyParish69)

**Comment by jonator** [comment]
@dogemos Is this an Epic?

**Comment by JeremyParish69** [comment]
This would call for removing KRT, TICK, CTK, CERBERUS, and HOPE. I think I can remove the assets from chain suggest and trader router quite easily. Should I go ahead with this?

**Comment by jonator** [comment]
@JeremyParish69 Sure! Feel free to open a draft PR if you'd like to collab. Also, be sure to [link this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) when you open the PR so we keep things automated and tidy.
