### ISSUE TITLE
[EPIC] LBP 2.0 

### ISSUE THREAD

**Issue by syed8rahman** [osmosis-labs/osmosis-frontend#426]
- [ ] LBP Homepage or dashboard
- [ ] Details page for specific LBP 
- [ ] Buy modal for participating in LBP

**Comment by jonator** [comment]
To be implemented by omniflix team
